export const BASE_URL = "http://localhost:4000/";
export const REGISTRATION_URL = "api/auth/register";
export const LOGIN_URL = "api/auth/login";
export const AUTH = "api/auth/me";
export const LOGOUT = "api/auth/logout";
export const FIND_USER = "api/users?search=";
export const CONVERSATION_ID = "api/conversations/direct";
export const RECENT_CONVERSATION = "api/conversations";
export const SEND_MESSAGE = "api/conversations/conversation_id/messages";